Basic structure and style for Homescreen and Header
nicmart-dev/feedmenow pull request #29
Opened 2024-07-16 21:30 UTC by juliakimseohyeon

Hi team, when you have a moment please take a look at the Homescreen and Header. Thank you 😊

2024-07-18 23:02 UTC, juliakimseohyeon commented
Related to Ticket #21

2024-07-18 23:56 UTC, nicmart-dev commented
@juliakimseohyeon great job matching with the mockup!

A few notes:

1. As login will be taken opportunistically, I suggest to hide the login icon behind a feature toggle (or comment out the associated code) and also same for the saved recipes section.
2. small enhancement, you used a logout instead of login icon.
3. Add `.DS_Store` to `.gitignore`

2024-07-19 00:02 UTC, nicmart-dev requested changes
@juliakimseohyeon great job matching with the mockup!

A few notes:
1. As login will be taken opportunistically, I suggest to hide the login icon behind a feature toggle (or comment out the associated code) and also same for the saved recipes section.
2. small enhancement, you used a logout instead of login icon.
3. Add `.DS_Store` to `.gitignore`

2024-07-22 05:17 UTC, nicmart-dev requested changes
Nice job Julia on footer and change language!

A few comments:
- I still see a few `.DS_Store` files in the PR.
- When changing language, some text is still in English (ie. Hungry Chef and "Show me" button, and I think app name itself should be translated). Also when clicking that button in another language, language reverts back to English
![image](https://github.com/user-attachments/assets/87829689-be3e-4e43-8e01-f80927fef375)

2024-07-23 19:59 UTC, juliakimseohyeon commented
Hi @nicmart-dev, thanks for pointing those out! I've removed the cached `.DS_Store` files and added a onSubmit function to the form on the home page. This should prevent the language from reverting back to English now.

2024-07-23 20:11 UTC, nicmart-dev approved these changes

2024-07-23 20:38 UTC, nicmart-dev reviewed
Some minor comments regarding files at the root.

2024-07-23 20:38 UTC, nicmart-dev commented on tailwind.config.js
I think this file at the root should be removed, and only the one in client folder remain.

2024-07-23 20:38 UTC, nicmart-dev commented on package.json
I think the changes should be undone, as those dependencies belong in the client folder, not at the root.

2024-07-26 22:36 UTC, merged